name: Publish Parent POM

on:
  push:
    tags:
      - 'v*.*.*'  # Alleen bij tags zoals v1.0.0, v1.0.1, etc.

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 23
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Publish to GitHub Packages
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
